build: make upload-artifact names unique
A GitHub Action matrix lets you run a workflow multiple times using
different parameters:

    https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

The matrix of the python-test.yml's GitHub Action is uploading a
coverage file per python-version in the matrix.

This is no longer allowed by actions/upload-artifact. See its README:

    https://github.com/actions/upload-artifact/blob/cf8714cfeaba5687a442b9bcb85b29e23f468dfa/README.md#not-uploading-to-the-same-artifact

Fixes errors like:

    ```
    Run actions/upload-artifact@master
    With the provided path, there will be 1 file uploaded
    Artifact name is valid!
    Root directory input is valid!
    Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
    ```

The example above from:

    https://github.com/edx/commercetools-python-sdk/actions/runs/7289547220/job/19864387471?pr=1_